name: Deploy ReceiveFlow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self hosted
      - Linux
      - ARM

    steps:
      - name: Deploy application
        run: |
          cd /home/pi/personalDev/receiveflow/scripts
          chmod +x deploy.sh
          ./deploy.sh
